server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jishi
    username: root
    password: 657826973YANGyan?
#    username: jishi
#    password: WeKCSAME52dEdTBL
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 417695971@qq.com #QQ邮箱
    password: drvvnzlqxbddcahd #客户端授权码
    protocol: smtp #发送邮件协议
    default-encoding: utf-8
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
      max-request-size: 100MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    驼峰命名问题
#    map-underscore-to-camel-case: true
